In [2]:
#1. Importa el paquete NUMPY bajo el nombre np.
import numpy as np

#2. Imprime la versión de NUMPY y la configuración.
print(np.__version__)

1.26.4


#3. Genera un array tridimensional de 2x3x5 con valores aleatorios. Asigna el array a la variable "a"

Desafío: hay al menos tres maneras fáciles que usan numpy para generar arrays aleatorios. ¿Cuántas formas puedes encontrar?

In [3]:
a = np.random.random((2, 3, 5))
print(a)

[[[0.59148553 0.43935286 0.4655509  0.70928217 0.96116432]
  [0.50102742 0.48556397 0.13443505 0.96978664 0.25473508]
  [0.27158613 0.09806125 0.90563585 0.00452989 0.81280366]]

 [[0.3362974  0.97546318 0.00506078 0.72137237 0.24946827]
  [0.90718425 0.20174529 0.26809433 0.74590181 0.91986297]
  [0.41958045 0.33574184 0.12658451 0.53106393 0.7363637 ]]]


#5. Crea un array tridimensional de 5x2x3 con todos los valores igual a 1.
#Asigna el array a la variable "b"

In [4]:
b = np.ones((5, 2, 3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#7. ¿Tienen a y b el mismo tamaño? ¿Cómo lo demuestras en código Python?

In [6]:
array_sizes = a.size == b.size
print(array_sizes)

True


#8. ¿Es posible sumar a y b? ¿Por qué sí o por qué no?

In [8]:
#No es posible porque tienen el mismo tamaño pero no la misma forma

#9. Transpone b para que tenga la misma estructura que a (es decir, se convierta en un array de 2x3x5). Asigna el array transpuesto a la variable "c".

In [10]:
c = np.transpose(b, (1, 2, 0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#10. Intenta sumar a y c. Ahora debería funcionar. Asigna la suma a la variable "d". Pero, ¿por qué funciona ahora?

In [11]:
#Funciona porque tienen la misma forma
d = a + c
print(d)

[[[1.59148553 1.43935286 1.4655509  1.70928217 1.96116432]
  [1.50102742 1.48556397 1.13443505 1.96978664 1.25473508]
  [1.27158613 1.09806125 1.90563585 1.00452989 1.81280366]]

 [[1.3362974  1.97546318 1.00506078 1.72137237 1.24946827]
  [1.90718425 1.20174529 1.26809433 1.74590181 1.91986297]
  [1.41958045 1.33574184 1.12658451 1.53106393 1.7363637 ]]]


#11. Imprime a y d. ¿Notas la diferencia y la relación entre los dos arrays en términos de los valores? Explica.

In [12]:
#La suma es cada posición más 1 porque el array c son solo unos

#12. Multiplica a y c. Asigna el resultado a e.


In [13]:
e = a * c
print(e)

[[[0.59148553 0.43935286 0.4655509  0.70928217 0.96116432]
  [0.50102742 0.48556397 0.13443505 0.96978664 0.25473508]
  [0.27158613 0.09806125 0.90563585 0.00452989 0.81280366]]

 [[0.3362974  0.97546318 0.00506078 0.72137237 0.24946827]
  [0.90718425 0.20174529 0.26809433 0.74590181 0.91986297]
  [0.41958045 0.33574184 0.12658451 0.53106393 0.7363637 ]]]


#13. ¿Es e igual a a? ¿Por qué sí o por qué no?

In [14]:
#si es igual, porque al multiplicar cada posición por 1, nos devuelve el mismo valor 

#14. Identifica los valores máximos, mínimos y medios en d. Asigna esos valores a las variables "d_max", "d_min" y "d_mean"

In [15]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9754631750924936
1.004529893664254
1.5028261936203753


#15. Ahora queremos etiquetar los valores en d. Primero crea un array vacío "f" con la misma forma (es decir, 2x3x5) que d usando `np.empty`.

In [16]:
f = np.empty(d.shape)
print(f)

[[[0.59148553 0.43935286 0.4655509  0.70928217 0.96116432]
  [0.50102742 0.48556397 0.13443505 0.96978664 0.25473508]
  [0.27158613 0.09806125 0.90563585 0.00452989 0.81280366]]

 [[0.3362974  0.97546318 0.00506078 0.72137237 0.24946827]
  [0.90718425 0.20174529 0.26809433 0.74590181 0.91986297]
  [0.41958045 0.33574184 0.12658451 0.53106393 0.7363637 ]]]


#16. Rellena los valores en f. Para cada valor en d, si es mayor que d_min pero menor que d_mean, asigna 25 al valor correspondiente en f.
Si un valor en d es mayor que d_mean pero menor que d_max, asigna 75 al valor correspondiente en f.
Si un valor es igual a d_mean, asigna 50 al valor correspondiente en f.
Asigna 0 al valor correspondiente(s) en f para d_min en d.
Asigna 100 al valor correspondiente(s) en f para d_max en d.
Al final, f debería tener solo los siguientes valores: 0, 25, 50, 75 y 100.
Nota: no necesitas usar Numpy en esta pregunta.

In [18]:
for i in range(d.shape[0]):        
    for j in range(d.shape[1]):    
        for k in range(d.shape[2]):  
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100

print(f)

[[[ 75.  25.  25.  75.  75.]
  [ 25.  25.  25.  75.  25.]
  [ 25.  25.  75.   0.  75.]]

 [[ 25. 100.  25.  75.  25.]
  [ 75.  25.  25.  75.  75.]
  [ 25.  25.  25.  75.  75.]]]


#17. Imprime d y f. ¿Tienes el f esperado?
Por ejemplo, si tu d es:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Tu f debería ser:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])


#18. Pregunta de bonificación: en lugar de usar números (es decir, 0, 25, 50, 75 y 100), ¿cómo usar valores de cadena 
("A", "B", "C", "D" y "E") para etiquetar los elementos del array? Esperas el resultado sea:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
De nuevo, no necesitas Numpy en esta pregunta.

In [19]:
for i in range(d.shape[0]):        
    for j in range(d.shape[1]):    
        for k in range(d.shape[2]):  
            if d[i, j, k] == d_min:
                f[i, j, k] = "A"  
            elif d[i, j, k] == d_mean:
                f[i, j, k] = "C"  
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i, j, k] = "E"  
            elif d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i, j, k] = "B"  
            elif d[i, j, k] == d_max:
                f[i, j, k] = "D"

print(f)

ValueError: could not convert string to float: 'E'